"""init_revision

Revision ID: 04485743d6c8
Revises: 
Create Date: 2023-09-25 14:01:45.855444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04485743d6c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_version',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('project_data',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_version_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('planed', sa.Float(), nullable=True),
    sa.Column('in_fact', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_version_id'], ['file_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_data')
    op.drop_table('project')
    op.drop_table('file_version')
    # ### end Alembic commands ###
